"""Exception raised for errors in the Batch management."""

from connector.src.custom.exceptions.gti_base_error import GTIBaseError


class GTIBatchError(GTIBaseError):
    """Exception raised for errors in the Batch management."""

    ...
