"""Exception raised for errors in the configuration."""

from connector.src.custom.exceptions.gti_base_error import GTIBaseError


class GTIConfigurationError(GTIBaseError):
    """Exception raised for errors in the configuration."""

    ...
